# Website details
name: "mattias.pw / projects"
description: ""
email: "hello(at)mattias.pw"
author: "Mattias Hagberg"
lang: "en"
locale: "en_SE"

# Jekyll
paginate: 10
markdown: kramdown
timezone: Europe/Stockholm
paginateLabel: page
paginate_path: "page/:num"
permalink: pretty
baseurl: 

# Includes
addthisId: ""
disqusUsername: "mattias-pw"
googleAnalyticsId: "UA-33644854-1"

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/projects"
    change_frequency_name: "daily"
    priority_name: "1.00"
