# Website details
name: "mattias.pw / pens"
description: ""
email: "hello@mattias.pw"
author: "Mattias Hagberg"
lang: "en"
locale: "en_SE"
repository: pestbarn/pestbarn.github.io

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: Europe/Stockholm
paginateLabel: page
paginate_path: "page/:num"
permalink: pretty
baseurl: /pens

# Includes
addthisId: ""
disqusUsername: "mattias-pw"
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"
